city_names = {
    "ACTON": ["ACTON, CA", "ACTON", "ACTION CA", "ACTON", "ACTON CA"],
    "ALPINE": ["ALPINE CA", "ALPINE"],
    "AGOURA HILLS": [
        "AGOURA CA",
        "AGOURA  CA",
        "AGOURA HILLS CA",
        "AGOURA CA",
        "AGOURA HILLS",
        "AGOURA",
        "AGOURA HILLS",
    ],
    "AGUA DULCE": [
        "AGUA DULCE CA",
        "AGUADULCE CA",
        "AGUA DULE CA",
        "AGUAL DULCE CA",
        "AFUA DULCE CA",
        "AGUA DUICE CA",
        "AFUA DULCE CA",
        "AGAU DULCE CA",
        "AGUA DUCE CA",
        "AGUA DUICE CA",
        "AGUA DULCA CA",
        "AGUA DULCE",
        "AGUA DULE CA",
        "AGUA DYLCE CA",
        "AGUADULCE CA",
        "AQUA DULCE CA",
        "AUGA DULCE CA",
        "AGUAL DULCE CA",
        "AGUD DULCE",
    ],
    "ALHAMBRA": ["ALHAMBRA", "ALHANBRA CA", "ALHAMBRA CA"],
    "ALPINE BUTTE": ["ALPINE BUTTE CA", "ALPINEBUTTE CA", "ALINE BUTTE CA"],
    "ALTADENA": [
        "ALTADENA CALIF",
        "ALTADENA CA",
        "ALTADEN CA",
        "ALTADENA",
        "ALTA DENA CA",
    ],
    "ANAVERDE": ["ANAVERDE CA", "ANA VERDE CA"],
    "ANTELOPE ACRES": [
        "ANTELOPE VALLEY CA",
        "ANTELOPE ACRES",
        "ANTLEOPE ACRES CA",
        "ANTELOPE ACRES CA",
        "ANTELOPE AVRES CA",
        "ANELOPE ACRES CA",
        "ANTELOPE ACRES",
        "ABTELOPE ACRES CA",
        "ANTLOPE ACRES CA",
        "ANTELOPOE ACRES CA",
        "ANTELOPE ACRS CA",
        "ANTELOPE CA",
        "ANTLEOPE ACRES CA",
        "ANTELOPE ARCES CA",
        "ANETLOPE ACRES CA",
        "ANTELOPE ACRSE CA",
        "ANTELPE ACRES CA",
        "ANTLEOPE ACRES CA",
    ],
    "ARCADIA": ["ARCADIA CALIF", "ARCADIA", "ARCADIA CA", "ARADIA CA", "CA"],
    "ARLETA": ["ARLETA CA", "ARITA CA"],
    "ARTESIA": ["ARTESIA, CA", "ARETESIA CA", "ARTESIA CA"],
    "ATHENS": ["ATHENS CA"],
    "AVALON": ["AVALON  CA", "AVALON CA", "AVALON"],
    "AVOCADO HEIGHTS": ["AVOCADO HEIGHTS CA"],
    "AZUSA": ["AZUSA", "AZUSA CA", "AZUSA CALIF"],
    "BALDWIN HILLS": ["BALDWIN HILLS CA"],
    "BALDWIN PARK": ["BALDWIN PK CA", "BALDWIN PARK", "BALDWIN PARK CA"],
    "BASSETT": ["BASSET CA", "BASSETT CA"],
    "BEL AIR": ["BEL AIR CA"],
    "BELL": ["BELL, CA", "BELL", "BELL CA"],
    "BELL GARDENS": ["BELL GARDENS C", "BELL GARDENS CA", "BELL GARDENS, CA"],
    "BELLFLOWER": [
        "BELLFLOWER CA",
        "BELLFLOWER AVE",
        "BELLFLOWER, CA",
        "BELLFLOWER  CA",
        "BELLFLOWER",
        "BELLFOWER, CA",
    ],
    "BEVERLY HILLS": [
        "BEVERLY HILLS CALIF",
        "BEVERLY HILLS, CA",
        "BEVERLY HILLS",
        "BEVERLY HILLS CA",
    ],
    "BLACK BUTTE": [
        "BLACK BUTT CA",
        "VBLACK BUTTE CA",
        "BLACK BUTTE CA",
        "BLACK BUTTE CA`",
        "BALCK BUTTE CA",
        "BLACK BUTTS CA",
        "BULACK BUTTE CA",
        "BLACK BUTTE",
    ],
    "BRADBURY": ["BRADBURY CA", "BRADBURY"],
    "BRENTWOOD": ["BRENTWOOD CA", "BRENTWOOD"],
    "BURBANK": [
        "BURBANK CA-",
        "BURBANK CALIF",
        "BURBANK CA A",
        "BURBANK CA",
        "BURBANK",
        "BURBANK VA",
        "BURBANK, CA",
    ],
    "BUTTE VALLEY": [
        "BUTTE VALLEY C",
        "BUTTE VALLEY CA",
        "BUTTE VALLEY VA",
        "BUTTE VALLEY",
    ],
    "CALABASAS": [
        "CALABASAS CA",
        "CALABASAS HILLS CA",
        "CALABASSAS CA",
        "CALABASAL CA",
        "CALABASAS",
        "CALABASAS CAL",
    ],
    "CALICHE": ["CALICHE", "CALICHE CA"],
    "CANOGA PARK": ["CANOGA PARK  CA", "CANOGA PARK CA", "CANOGA PARK"],
    "CANYON COUNTRY": [
        "CANYON COUNTR CA",
        "CANYON COUNTRY",
        "CANYON COUNTRY CA",
        "CANYON CNTRY CA",
    ],
    "CARSON": ["CARSON", "CARSON CA", "CARSON ST", "CARSON CALIF", "90746"],
    "CASTAIC": ["CASTAIC CA", "CASTICC CA"],
    "CENTURY CITY": ["CENTURY CITY CA"],
    "CERRITOS": ["CERRITOS CA", "CERRITOS/CA", "CERRITOS", "CERRITOS, CA"],
    "CHARTER OAK": ["CHARTER OAK CA"],
    "CHATSWORTH": [
        "CHATSWORTH,CA",
        "CHATSWORTH",
        "CHATWORTH CA",
        "CHATSWORTH CA",
        "CHATSWOTH CA",
        "CHATWSWORTH CA",
        "CHATSWORTH LAKE CA",
    ],
    "CITY OF INDUSTRY": [
        "CITY OF INDUSTRY",
        "CITY OF INDUSTRY CA",
        "INDUSTRY CA",
        "CITY INDUSTRY",
        "CITY INDUSTRY CA",
    ],
    "CITY TERRACE": ["CITY TERRACE CA"],
    "CLAREMONT": ["CLAREMONT CA", "CLAREMONT", "CLAREMONT  CA"],
    "COMMERCE": [
        "CITY OF COMMERCE",
        "CITY OF COMMERCE CA",
        "COMMERCE, CA",
        "COMMERCE CA",
    ],
    "COMPTON": [
        "COPMPTON CA",
        "COMTON CA",
        "COMPTON CA 90222",
        "COMPTON CA",
        "COMPTON",
        "WATTS",
        "WEST COMPTON",
        "CPMPTON CA",
        "COMPTON/CA",
        "COMPTON, CA",
    ],
    "CORNELL": ["CORNELL CA"],
    "COVINA": ["COVIN CA", "COVINA VA", "COVINA", "COVINA CA"],
    "CRYSTALAIRE": ["CRYSTALAIRE CA"],
    "CUDAHY": ["CUDAHAY CA", "CUDAHY, CA", "CUDAHY CA", "CUDAHY"],
    "CULVER CITY": ["CULVER CITY", "CULVER CITY CA", "CULVERCITY CA", "CULVER CITY,CA"],
    "CYPRESS": ["CYPRESS CA"],
    "DEL AIRE": ["DEL AIRE CA"],
    "DEL SUR": ["DEL SUR", "DEL SUR CA", "DELSUR CA"],
    "DIAMOND BAR": ["DIAMOND BAR CA", "DIAMOND BAR"],
    "DOMINGUEZ": [
        "DOMINGUEZ CA",
        "DOMIGUEZ CA",
        "DOMNINGUEZ CA",
        "DOMINGUEZ HILLS CA",
        "DOMINGUEZ",
        "DOMNIGUEZ CA",
        "DOMINGUES CA",
    ],
    "DOWNEY": ["DOWNEY CA 90241", "DOWNEY", "DOWNEY CA", "DOWNEY, CA"],
    "DUARTE": ["DUARTE CA", "DUARTEALE CA", "DUARTE CA", "DUARTE"],
    "EAST LOS ANGELES": [
        "E LOS ANGELES CA",
        "EAST LOS ANGELES CA",
        "EAST LOS ANGELE CA",
    ],
    "ELIZABETH LAKE": ["ELIZABETH LAKE CA", "ELIZABETH CA", "ELIZABETH LAKE"],
    "EL MONTE": [
        "EL MONTE / CALIFORNIA",
        "EL MONTE CA",
        "SO EL MONTE CA",
        "SIUTH EL MONTE CA",
        "ELMONTE CA",
        "EL MONTE",
        "SO. EL MONTE CA",
        "S. EL MONTE CA",
        "SOUTH EL MONTE",
        "SOUTH EL MOMNTE CA",
    ],
    "EL SEGUNDO": ["EL SEGUNDO CA", "EL SEGUNDO"],
    "ENCINO": ["ENCINO CA", "ENCINO, CA"],
    "FAIR OAKS RANCH": ["FAIR OAKS RANCH CA"],
    "FAIRMONT": ["FAIRMONT CA"],
    "FERNWOOD": ["FERNWOOD CA"],
    "FLORENCE": ["FLORENCE CA", "FLORENCE OR"],
    "FOOTHILL": ["FOOTHILL CA", "FOOTHILLS CA"],
    "GARDENA": [
        "GARDENA CALIF",
        "GARDENA CA",
        "GARDENA VA",
        "GARDENA",
        "GARDENA CA 90247",
    ],
    "GLASSELL PARK": ["GLASSELL PARK CA"],
    "GLENDALE": [
        "GLENDALE, CA",
        "GLENDA CA",
        "GLANDALE CA",
        "GLENDALE-CA",
        "GLENDALE CALIF",
        "GLENDALE & BURBANK, CA",
        "GLENDALE",
        "GLENDALE CA",
        "GLENOALE",
    ],
    "GLENDORA": ["GLENDORA CA", "GLENDORA"],
    "GORMAN": ["GORMAN", "GORMAN CA"],
    "GRANADA HILLS": ["GRANADA HILLS CA"],
    "GREEN VALLEY": [
        "GREEN VALLEY",
        "GREEN VALLEY CA",
        "GREN VALLEY CA",
        "GREEN VALLE CA",
    ],
    "HACIENDA HEIGHTS": [
        "HACIENDA HIEGHTS CA",
        "HACIENDA HGHTS CA",
        "HACIENDA HEIGHT CA",
        "HACIENDAHEIGHTS CA",
        "HACIENDA HEIGHTS C CA",
        "HACINDA HEIGHTS CA",
        "HACIENDA HGTS CA",
        "HACIENDA HEIGTHS CA",
        "HACIENDA  HEIGHTS CA",
        "HCIENDA HEIGHTS CA",
        "HACIENDA HTS CA",
        "HACIENDA HEIGHTS",
        "HACIENDA HEIGHTS CA",
        "HACIENA HEIGHTS CA",
    ],
    "HARBOR CITY": [
        "HARBOR CITY, CA",
        "HARBOR CIT CA",
        "HARBOR CTIY CA",
        "HARBOR CITY CA",
        "HARBOR CITY",
    ],
    "HAWAIIAN GARDENS": [
        "HAWAIIAN GARDNS CA",
        "HAWAIIAN GRADENS CA",
        "HAWAIIAN GARDENS",
        "HAWAIIAN GARDENS CA",
        "HAWAIIAN GDNS CA",
    ],
    "HAWTHORNE": [
        "HAWTHORNE, CA",
        "HAWTHORNE",
        "HAWTHORNE BLVD CA",
        "HAWTHORNE CALIF",
        "HAWTHRONE CA",
        "HAWTHORNE CA",
    ],
    "HERMOSA BEACH": [
        "HERMOSA BEACH",
        "HERMOSA BEACH CA",
        "HERMOSA BCH, CA",
        "HERMOSA BCH CA",
    ],
    "HIDDEN HILLS": ["HIDDEN HILLS CA"],
    "HIGH VISTA": [
        "HI VISATA CA",
        "HI VIST CA",
        "HIGH VISTA CA",
        "HI VISTA CA",
        "HI VISTA",
    ],
    "HOLLYWOOD": ["HOLLYWOOD CA"],
    "HOWARD": ["HOWARD CA"],
    "HUGHES LAKE": ["LAKE HUGES CA", "LAKE HUGHES", "HUGHES LAKE CA", "LAKE HUGHES CA"],
    "HUNTINGTON PARK": [
        "HUNTINGTON PK CA",
        "HUNTINGTON PARK CA",
        "HUNTINGTON PARK",
        "HUNTINGTON PARK, CA",
    ],
    "INGLEWOOD": ["INGLEWOOD, CA", "INGLEWOOD CA", "INGLWODD CA", "INGLEWOOD"],
    "IRWINDALE": ["IRWINDALE", "IRWINDALE CA"],
    "ISTHMUS": ["ISTHMUS CA", "ISTHMUS"],
    "JUNIPER HILLS": ["JUNIPER HILLS CA"],
    "KAGEL CANYON": ["KAGEL CANYON CA", "KAGEL CANYON"],
    "LA CANADA FLINTRIDGE": [
        "LA CANAD-FLT CA",
        "LA CANADA CA",
        "LA CANADA FLINTRIDGE CA",
        "LA CANANDA FLT CA",
        "LA CANADA FLT CA",
        "LA CANADA FLINT CA",
        "LA CANADA FLT",
        "LA CANADA FLT CA A",
        "LA CANADA FLT CA CA",
        "LA CANADA FLINTRIGE CA",
        "LA CANADA FLINTRUDGE CA",
        "LA CANADA-FLNTRDG CA",
        "LA CANAD-FLNTRDG CA",
        "LA CANADA FLNTRDG CA",
        "LA CANADA-FLINTRIDGE",
        "LA CANADA FLT CA T",
        "LA CANADA FL CA A",
        "LA CANADA-FLINTRIDGE CA",
    ],
    "LA CRESCENTA": [
        "LA CRESCENTA CA",
        "LACRESCENTA CA",
        "LA CRESENTA CA",
        "LA CRECENTA CA",
        "LA CRESCENTA",
        "LA CRESCENTA, CA",
        "LA CRESCENT CA",
        "LA CESCENT CA",
    ],
    "LA HABRA": ["LA HABRA CA"],
    "LA HABRA HEIGHTS": [
        "LA HABRA HTS CA",
        "LA HABRA HGTS CA",
        "LA HABRA HEIGHTS CA",
        "LA HABRA HGHTS CA",
    ],
    "LA MIRADA": ["LAMIRADA CA", "LA MIRADA, CA", "LA MIRADA", "LA MIRADA CA"],
    "LANCASTER": ['WHITE FENCE FARM CA', "LANCASTER CA", "LANCASTER", "WHITE FENCE FARM"],
    "LA PUENTE": [
        "LA PUENTE CA",
        "LA PUENTE",
        "LAPUENTE CA",
        "LA PUENTE CA CA",
        "LA PUENTA CA",
    ],
    "LA QUINTA": ["LA QUINTA CA"],
    "LA VERNE": ["LA VERN CA", "LA VERNE", "LA VERNE CA", "LAVERNE CA"],
    "LADERA": ["LADERA CA"],
    "LAKE BALBOA": ["LAKE BALBOA CA"],
    "LAKE ELIZABETH": [
        "ELIZABETJ LK CA",
        "ELIZABETH LK CA",
        "EIZABETH LAKE CA",
        "ELIZABETH LAKE CA",
        "LAKE HUGES CA",
        "ELIZABETH HILL CA",
        "ELZIBETH LK CA",
        "ELIZABETH LK DR",
        "LAKE ELIZABETH CA",
        "EIZABETH LK CA",
        "ELIZAABETH LAKE CA",
    ],
    "LAKE LOS ANGELES": [
        "LAKE LOS ANGELES",
        "LAKE LOS ANGELES CA",
        "LAKE LOS ANGLES CA",
        "LAKE LOS ANGELE CA",
        "LAK LOS ANGELES CA",
        "LOKE LOS ANGELE CA",
        "LAKE LOS ANGELES",
        "LAKE LOS ANGELES, CA",
        "LAKE LOS ANGELS CA",
        "LAKE L A CA",
        "LAKE LA CA",
        "LAKE LSO ANGELES CA",
    ],
    "LAKEVIEW TERRACE": ["LAKE VIEW TERRACE CA", "LAKEVIEW TERRACE CA"],
    "LAKEWOOD": ["LAKEWOOD CA", "LAKEWOOD", "LAKEWOOD, CA"],
    "LANCASTER": [
        "LANCASTER CAL",
        "LANCASTER CAELES CA",
        "LANCATER CA",
        "LANACASTER CA",
        "LANCASTER",
        "LANCASTE CA",
        "LANCASTERC CA",
        "LANASTER CA",
        "LANCASTER (LAKE LA) CA",
        "LACASTER CA",
        "LANCASTER CA",
        "LANCASTER, CA",
    ],
    "LAWNDALE": ["LAWNDALE", "LAWNDALE CA"],
    "LEBEC": ["LEBEC CA"],
    "LENNOX": ["LENNOX", "LENNOX CA"],
    "LEONA VALLEY": [
        "LEONA VALLEY CA",
        "LEONA VALLE CA",
        "LEONA VALLE CA",
        "LEONA VALLEY CA",
    ],
    "LITTLEROCK": [
        "LITTLEORCK CA",
        "LITTLEROCK",
        "LITTLEROCKCA",
        "LITTEROCK CA",
        "LITLEROCK CA",
        "LITTLE ROCK CA",
        "LITTLEROCK CA",
    ],
    "LLANO": ["LLANO, CA", "LIANO CA", "LLANO CA", "LLAND CA"],
    "LOMITA": ["LOMITA CA", "LOMITA"],
    "LONG BEACH": [
        "LONG BEACH, CA",
        "LONG  BEACH CA",
        "LONG BEACH CALIFORNIA",
        "LONG BEACH CALIF",
        "LONGBEACH CA",
        "LONG BEACH",
        "LONG BEACH CA",
        "LONG BEACH CA CA",
    ],
    "LOS ANGELES": [
        "LOS AGELES CA",
        "LOS ANGLELS CA",
        "LOS ANGELES CA 00",
        "LSO ANGELES CA",
        "LOS ANGE",
        "QOS ANGELES CA",
        "LOS ANGELES CA 91042",
        "LOS ANGELES",
        "EAST LOS ANGELES",
        "LOS ANGLES CA",
        "LO ANGELES CA",
        "LOS ANGELES (SYLMAR)",
        "LOS ANAGELES CA",
        "LOS ANGGELES CA",
        "L A CA",
        "LOS ANGELES C A",
        "LOS ANGELES, CA",
        "LA CA",
        "LOS ANEGELES CA",
        "LOS ANGELE CA",
        "LOS ANGELES",
        "LOS ANGELES CA CA",
        "LOS ANGELES CA.",
        "LOS ANGELES CAA",
        "LOS ANGELES CALIF",
        "LOS ANGELES, CA 90032",
        "LOS ANGELES, CA 90042",
        "LOS ANGELES,CA",
        "LOS ANGELES. CA",
        "LOS ANGELRES CA",
        "LOS ANGES CA",
        "LOS ANGGELES CA",
        "LOS ANGELES CA",
        "LOS ANGELES,CA. CA",
        "LOS ANGELES CAD CA",
        "LOS ANGELS CA",
        "LOS ANGELES/CA",
        "WEST LOS ANGELES CA",
        "LOSANGELES, CA",
        "LOS ANGELES  CA",
    ],
    "LOS NIETOS": ["LOS NIETOS CA"],
    "LYNWOOD": ["LYNWOOD, CA", "LYNWOOD CA", "LYNWOOD", "FIRESTONE CA"],
    "MALIBU": [
        "MALIBU VISTA",
        "MALIBU  CA",
        "MALIBU CALIF",
        "MALIBU,CA",
        "MALIBU, CA",
        "MALIBU LAKE CA",
        "MALIBU",
        "MALIBU CA",
    ],
    "MANHATTAN BEACH": [
        "MANHATTAN BCH CA",
        "MANHATTAN BCH, CA",
        "MANHATTAN BEACH",
        "MANHATTANBEACH CA",
        "MANHATTAN BCH",
        "MANHATTAN BEACH CA",
    ],
    "MARINA DEL REY": [
        "MARINA DL REY CA",
        "MARINA DEL RY CA",
        "MARINA DEL REY CA",
        "MARINA DE REY CA",
        "MARNIA DEL REY CA",
        "MARINA DEL REY",
        "MARINA DEL REY, CA",
        "MARINA DEL REY CAA",
        "MARINA DEL REY C",
    ],
    "MAYWOOD": ["MAYWOOD CA", "MAYWOOD/CALIFORNIA"],
    "MISSION HILLS": ["MISSION HILLS CA"],
    "MONROVIA": ["MONROVIA CA"],
    "MONTE NIDO": ["MONTE NIDO CA"],
    "MONTEBELLO": ["MONTEBELLO", "MONTBELLO CA", "MONTEBELLO CA"],
    "MONTEREY PARK": [
        "MONTEREY  PARK CA",
        "MONTEREY PRK CA",
        "MONTEREY PARK CA",
        "MONTEREY PK CA",
    ],
    "MONTROSE": ["MONTROSE CA"],
    "MOUNT BALDY": ["MT BALDY CA", "MOUNT BALDY CA"],
    "MOUNT GLEASON": [
        "MOUNT GLEASON CA",
        "MT GLEASON CA",
        "MT GLE<SON CA",
        "NT GLEASON CA",
        "MT GLEASON",
    ],
    "MOUNT WATERMAN": [
        "MOUNT WATEMAN CA",
        "MT WATERMAN",
        "MOUNT WATERMAN",
        "MOUNT WATERMAN CA",
        "MONT WATERMAN CA",
        "MOUNT WATERMA CA",
        "MT WATERMAN CA",
    ],
    "MOUNT WILSON": ["MOUNT WILSON CALIF", "MT WILSON CALIF", "MOUNT WILSON CA"],
    "NEENACH": ["NEENACH CA"],
    "NEWHALL": ["NEWHALL", "NEWHALL CA"],
    "NORTH HILLS": ["NORTH HILLS CA", "NORTH HILLS"],
    "NORTH HOLLYWOOD": [
        "NORTH HOLLYWOOD CA",
        "NORTH HOLLYWOOD, CA",
        "N. HOLLYWOOD CA",
        "NO HOLLYWOOD CA",
        "N HOLLYWOOD CA",
        "NORTH HOLLYWOOD CALIF",
        "NORTH HOLLYWOOD",
    ],
    "NORTHRIDGE": ["NORHTRIDGE CA", "NORTHRIDGE CA", "GE CA"],
    "NORWALK": ["NORWALK", "NORWALK, CA", "NORWALK CA", "NORWAL CA", "NORWALK/CA"],
    "PACIFIC PALISADES": [
        "PASIFIC PALISADES",
        "PACIFIC PLSDS CA",
        "PACIFIC PALISADES CA",
        "PACIFIC PALISAADES CA",
        "PACIFIC PALISADES",
        "PACIFIC PALASADES CA",
        "PACIFIC PALISADE",
        "PACIFIC PALISADES CALIF",
    ],
    "PACOIMA": ["PACOIMA CA", "PACOIMA"],
    "PALMDALE": [
        "PALMDALE AC",
        "PALMDALE CA",
        "PALMDLE CA",
        "PALMDAEL CA",
        "PALMDALE CAQ93551",
        "PALMDALE  CA",
        "WEST PALMDALE CA",
        "PALMDALE CALIFORNIA",
        "PALMADALE CA",
        "PALMDALE",
        "PALMDALE CAL",
        "PLAMDALE CA",
        "PALMDALE CALIF",
        "PALDMALE CA",
        "W PALMDALE CA",
        "PALAMDALE CA",
        "PAMLDALE CA",
        "PALMDALE CA CA",
    ],
    "PALOS VERDES": ["PALOS VERDES CA"],
    "PALOS VERDES ESTATES": [
        "PALOS VERDES EST CA",
        "PALOS VERDES ESTATE CA",
        "PALOS VERDES EST, CA",
        "PALOS VERDES ESTATES CA",
        "PLS VRDS EST CA",
    ],
    "PALOS VERDES PENINSULA": [
        "PALOS VERDES PNSLA CA",
        "PALOS VERDES PENIN CA",
        "PALOS VRDS PNSL CA",
        "PALOS VERDES PNLA CA",
        "PALOS VERDES PENN CA",
        "PALOS VERDES PNSL CA",
        "PALOS VERDES PENNS CA",
        "PALOS VERDES PEN CA",
        "PLS VRDS PNSL CA",
        "PLS VRDS PNSLA CA",
    ],
    "PANORAMA CITY": ["PANORAMA CITY CA"],
    "PARAMOUNT": [
        "PARAMOUNT CA",
        "PARAMOUNT  CA",
        "PARAMOUNT CALIF",
        "PARAMOUNT, CA",
        "PARAMOUNT",
        "PARAMOUNT,CA",
    ],
    "PASADENA": ["PASDENA CA", "PASADENA CA", "PASADENA CALIF", "PASADENA"],
    "PEARBLOSSOM": [
        "PEARBLOSSOM",
        "PEARBLOSSOOM CA",
        "PEARLBLOSSOM CA",
        "PEARBLOSSOM",
        "PEARLAND CA",
        "PEARBLOSSSOM CA",
        "PERLBLOSSOM CA",
        "PEARBLOSSOMCA",
        "PEARLBLOSSOM",
        "PEARBLOSOM CA",
        "PEARBLOSSON CA",
        "PEARBLOSSOM CA",
        "PEARLBLOSSM CA",
        "PEARBOSSOM CA",
        "PEARBLOOSOM CA",
        "PEARBLASSOM CA",
        "PEARBLOOM CA",
        "PEALBLOSSOM CA",
        "PEAR BLOSSOM CA",
        "PEARLBLOSSSOM CA",
    ],
    "PHILLIPS RANCH": ["PHILLIPS RANCH CA"],
    "PICO RIVERA": ["PICO RIVERA", "PICO RIVERA CA"],
    "PLAYA DEL REY": [
        "PLAY DEL REY CA",
        "PLAYA DEL REY,CA",
        "PLAYA DEL REY, CA",
        "PLAYA DEL REY",
        "PLAYA DEL REY CA",
    ],
    "PLAYA VISTA": ["PLAYA VISTA", "PLAYA VISTA CA", "PLAYA VISSTA CA"],
    "POMONA": ["POMONA CA", "POMONA"],
    "PORTER RANCH": ["PORTER RANCH  CA", "PORTER RANCH", "PORTER RANCH CA"],
    "QUARTZ HILL": [
        "QUARTZ HILL CA",
        "QUARTZ HILL",
        "QUARTZ HILLS CA",
        "QUARTE HILL CA",
        "QUARTZ CA",
        "QUARZ HILL CA",
        "QUARTZ HILL, CA",
        "QUARTZ HILL CI",
        "QUARTZ HIL CA",
    ],
    "RANCHO DOMINGUEZ": [
        "RANCHO DOMINGUEZ CA",
        "RANCHO DOMINGUEZ",
        "RANCH DOMINGUEZ CA",
        "RANCH DOMINGUEZ CA ",
        "RANCHO DOMINGUEZ",
        "EAST RANCHO DOMINGUEZ CA",
        "RNCHO DOMINGZ CA",
        "RANCHO DOMIGUEZ CA",
    ],
    "RANCHO PALOS VERDES": [
        "RCH PALOS VRDS CA",
        "RCH PALOS VRD CA",
        "RNCHO PALOS VRDS CA",
        "RANCHO PALOS VERDES",
        "RANCHO PALOS VRDS CA",
        "RANCHO PALOS VERDES CA",
        "RANCHO PLS VERDES CA",
        "RANCHO PALOS VERDE CA",
        "RANCHO PALOS VERDES",
        "RCH PALOS VRD",
        "RANCHO PALOS VERD CA",
        "RNCHO PLS VRD CA",
        "RCH PALOS VERDES CA",
    ],
    "REDMAN": ["REDMAN CA", "REDMAN AVE", "REDMAN C", "RDEMAN CA"],
    "REDONDO BEACH": [
        "REDONDO BCH CA",
        "REDONDO BEACH, CA",
        "REDONDO BEACH CA",
        "REDONDO BEACH",
        "REDONDO BCH, CA",
    ],
    "RESEDA": ["RESEDA CA"],
    "ROLLING HILLS": [
        "ROLLING HILLS",
        "ROLLING HILLS CA",
        "ROLLING HLS CA",
        "ROLLING HILS CA",
    ],
    "ROLLING HILLS ESTATES": [
        "ROLLING HILLS ESTATE CA",
        "ROLLING HILLS ES CA",
        "RLLNG HLS EST CA",
        "ROLL HILLS ESTATES CA",
        "ROLLING HILLS ESTS CA",
        "RLLNG HLS ES CA",
        "ROLLING HILLS ESTATES",
        "ROLLING HILLS ESTAT CA",
        "ROLLING HILLS EST CA",
        "RLNG HLS EST CA",
        "ROLLINGS HILLS CA",
        "ROLLING HILLS ESTATES CA",
        "RLLNG HLS EST CAA",
    ],
    "ROOSEVELT": [
        "ROOSEVET CA",
        "ROOSVELTT CA",
        "ROOSEVEL CA",
        "ROOEVELT CA",
        "ROOSVELT CA",
        "ROOSEVELTY CA",
        "ROOSEVELT CA",
    ],
    "ROSAMOND": ["ROSAMOND CA"],
    "ROSEMEAD": ["ROSEMEAD", "ROSEMEAD CA"],
    "ROSEWOOD": ["ROSEWOOD CA"],
    "ROWLAND HEIGHTS": [
        "ROWLAND HGHTS CA",
        "ROWLAND HEIGHTS CCA CA",
        "ROWLAND HTS CA",
        "ROWLAND HEGHTS CA",
        "ROWLAN HEIGHTS CA",
        "ROWLAND HGHTS CA CA",
        "ROWLAND HGTS CA",
        "ROWLAND HEIGHTS CA",
        "ROWLAND HEIGHT CA",
        "ROWLAND HEUGHTS CA",
        "RORLAND HEIGHTS CA",
        "ROWLAND HEIGTHS CA",
    ],
    "SAN DIMAS": ["SAN DIMAS", "SAN DIAMS CA", "SAN DIMAS CA"],
    "SAN FERNANDO": ["SAN FERNANDO CA", "SAN FERNADO CA"],
    "SAN GABRIEL": [
        "SAN GABRIEL VA",
        "SAN BABRIEL CA",
        "SAN GABRIE CA",
        "NORTH SAN GABRIEL CA",
        "SAN GABRIEL",
        "SAN GABRIEL CA",
        "SAN GRABRIEL CA",
    ],
    "SAN MARINO": ["SAN MARINO CA"],
    "SAN PEDRO": ["SAN PEDRO, CA", "SAN PEDRO CA", "LA SAN PEDRO CA"],
    "SANTA CLARITA": [
        "SANTA CLARITA PL",
        "SANTA CLARITA DR",
        "SANTA LARITA CA",
        "SANTA CLASITA CA",
        "SANYA CLARITA CA",
        "SANTA CLARITA CALIFORNIA",
        "ANTA CLARITA CA",
        "SANTA CLARITA 91321",
        "SANTA CLARITA",
        "SANTA CLARITA VA",
        "SANAT CLARITA CA",
        "SAANTA CLARITA CA",
        "SANTA CLARITA CA,",
        "SANTA CLARITA CA",
        "SANTA CLARITA WAY",
        "SANA CLARITA CA",
    ],
    "SANTA FE SPRINGS": [
        "SANTA FE SPGS CA",
        "SANTA FE SPRINGS CA",
        "SANTA FE SPRNGS CA",
        "SANTA FE SPRINGS",
        "SANTA FE SPRINGS CALIF",
        "SANTA FE SPRINGS, CA",
    ],
    "SANTA MONICA": [
        "SANTA MONICA  CA",
        "SANTA MONICA CA",
        "SANTA MONICA, CA",
        "SANTA MONICA CALIF",
        "SANTA MONICA C",
        "SANTA MONICA",
    ],
    "SAUGUS": ["SAUGUS", "SAUGUS CA", "SAUGU CA"],
    "SAWMILL MOUNTAIN": [
        "SAWHILL MT CA",
        "SAWMILL MT",
        "SAWHILL MOUNTAIN CA",
        "SAWMILL MOUNTAIN CA",
        "SAWMILL MOUNTAIN RD",
        "SAWVILLE MT",
        "SAWMILL MT CA",
        "SAWMILL MOUNTAIN",
    ],
    "SEPULVEDA": ["SEPULVEDA CA"],
    "SHADOW HILLS": ["SHADOW HILLS CA"],
    "SHERMAN OAKS": ["SHERMAN OAKS CA", "SHERMAN OAKS"],
    "SIERRA MADRE": ["SIERRA MADRE CA"],
    "SIGNAL HILL": [
        "SIGNAL HILL",
        "SIGNAL HILL, CA",
        "SIGNAL CA",
        "SIGNAL HILLS CA",
        "SIGNAL HILL CA",
    ],
    "SILVER LAKE": ["SILVER LAKE CA"],
    "SIMI VALLEY": ["SIMI VALLEY CA"],
    "SOUTH EL MONTE": ["S EL MONTE CA", "SOUTH EL MONTE CA"],
    "SOUTH GATE": [
        "SOUTH GATE/CA",
        "SOUTH GATE/CALIFORNIA",
        "SO GATE CA",
        "SOUTH GATE / CA",
        "SOUTHGATE CA",
        "SOUTH GATE CA",
        "SOUTH GATE",
        "SOUTH GATE,  CA",
        "SOUTH GATE CALIF",
    ],
    "SOUTH PASADENA": [
        "SOUTH PASADENA CA",
        "S PASADENA CA",
        "SOUTH PASADENA",
        "SO.PASADENA CA",
        "SO PASADENA CA",
    ],
    "SOUTH SAN GABRIEL": [
        "SOUTH GRAND GABRIEL CA",
        "SOUTH SAN GRABRIEL CA",
        "SOUTH GABRIEL CA",
        "SOUTH SAN GABRIE CA",
        "S.SAN GABRIEL CA",
        "S SAN GABRIEL CA",
        "SOUTH SAN GABRIEL CA",
        "SO. SAN GABRIEL CA",
        "SO SAN GABRIEL CA",
    ],
    "SOUTH WHITTIER": ["SOUTH WHITTIER CA"],
    "STEVENSON RANCH": [
        "STEVENSON RNH CA",
        "STEVENSON RANCH  CA",
        "STEVENSON RANCH CA",
        "STEVENSON CA",
        "STENSON RANCH CA",
        "STEVENSON RANCH",
    ],
    "STUDIO CITY": ["STUDIO CITY", "STUDIO CITY CA"],
    "SUN VALLEY": [
        "SUN VALLEY CA",
        "SAN VALLEY CA",
        "SUN VALLEY CALIF",
        "SUN VALLY CA",
    ],
    "SUN VILLAGE": [
        "SNU VILLAGE CA",
        "SIN VILLAGE CA",
        "SUN VILLAGE",
        "SUN VILLAGE CA",
        "SUNVILLAGE CA",
        "SUN VILLAGAE CA",
        "SUN VILLLAGE CA",
        "SU VILLAGE CA",
        "SUN VILAGE CA",
        "SUN VILLAGE CA`",
        "SUN VALLAGE CA",
        "SUN VIILAGE CA",
        "SUN VILLAAGE CA",
    ],
    "SUNLAND": ["SUNLAND, CA", "SUNLAND", "SUNLAND CA"],
    "SYLMAR": ["SYLMAR CA A", "SYLMAR", "SYLMAR CA"],
    "TARZANA": ["TARZANA CA"],
    "TEMPLE CITY": [
        "TEMPLE CIT CA",
        "TEMPLE CITY CA",
        "TEMPLE CITY  CA",
        "TEMPLE CITY",
    ],
    "THOUSAND OAKS": ["THOUSAND OAKS CA"],
    "TOLUCA LAKE": ["TOLUCA LAKE CA", "TOLUCA TERRACE CA"],
    "TOPANGA": [
        "TOPANGA CANYON CA",
        "TOPANGA,CA",
        "TOPONGA CA",
        "TOPANGA  CA",
        "TOPANGA, CA",
        "TOPANGA CYN",
        "TOPANGA CA CA",
        "TOPANGA CYN CA",
        "TOPANGA",
        "TOPANGA CA",
        "TOPANGA CANYON",
    ],
    "TORRANCE": [
        "TORRANCE",
        "TORRANCE CA",
        "TORRANC CA",
        "TORRANCE  CA",
        "TORRANC CA",
        "TORRANCE",
        "TORRANCE  CA",
        "TORRANCE, CA",
        "TRRANCE CA",
        "TORRANCE,CA",
    ],
    "TUJUNGA": ["TUJUNGA CA", "TUJUNGA"],
    "UNIVERSAL CITY": ["UNIVERSAL CITY CA", "UNIVERSAL CITY"],
    "UNINCORPORATED/UNKNOWN": ["UNINCORPORATED CA", "Unknown", "VACANT", "VILLAGE CA"],
    "VAL VERDE": [
        "VAL VERDE",
        "VAL VERDE CA",
        "VAL VERDE PARK CA",
        "VAL VERD CA",
        "VALVERDE CA",
    ],
    "VALENCIA": [
        "VALENCIA CALIF",
        "VALENCIA CATA CA",
        "VALENCIA CA 91381",
        "VELENCIA CA",
        "VALENCIA CALIFORNIA",
        "VALENCIA",
        "VALENCIA CT",
        "VALENCIA, CA",
        "VALENCIA CA",
        "VALNCIA CA",
    ],
    "VALINDA": ["VALINDA CA", "VALINDA, CA"],
    "VALLEY GLEN": ["VALLEY GLEN CA"],
    "VALLEY VILLAGE": [
        "VALLEY VILLAGE",
        "VALLEY VILLAGE CAQ91607",
        "VALLEY VILLAGE CA",
    ],
    "VALYERMO": ["VALYERMO", "VALYERNO CA", "VALLYERMO CA", "VALYERMO CA"],
    "VAN NUYS": ["VAN NUYS CA", "VAN NUYS CALIF", "VAN NUYS", "VAN NUYS, CA"],
    "VENICE": ["VENICE, CA", "VENICE CA A", "VENICE", "VENICE CA", "VENICE  CA"],
    "VERNON": ["VERNON CA", "VERNON"],
    "VIEW PARK": ["VIEW PARK CA"],
    "WALNUT": ["WALNUT CA", "WALNU CA", "WALNUT"],
    "WALNUT PARK": ["WALNUT PARK CA"],
    "WATTS": ["WATTS CA"],
    "WEST COMPTON": ["WEST COMPTON CA"],
    "WEST COVINA": [
        "WEST COVIA CA",
        "W COVINA CA",
        "WEST COVINA",
        "WEST COVIN CA",
        "WEST COVINA CA",
    ],
    "WEST HILLS": ["WESTHILLS CA", "WEST HILLS CA"],
    "WEST HOLLYWOOD": [
        "W HOLLYWOOD CA",
        "WWEST HOLLYWOOD CA",
        "WEST HOLLYWOOD CA",
        "WEST HOLLYWOOD",
        "9EST HOLLYWOOD CA",
        "WEST HOLLYWOOD  CA",
        "WEST HOLLYWOO CA",
        "WEST HOLLYWOOD, CA",
    ],
    "WESTCHESTER": ["WESTCHESTER", "WESTCHESTER CA"],
    "WESTLAKE VILLAGE": [
        "WESTLAKE VLG CA",
        "WESTLAKE VILLAGE",
        "WESTLAKE VILLG CA",
        "WESTLAKE VILLAGE CA",
        "WESTLAKE VILLGE CA",
        "WESTLAKE VILLAGE  CA",
        "WEST LAKE VILLAGE CA",
    ],
    "WESTRIDGE": ["WESTRIDGE CA"],
    "WHITTIER": [
        "WHITIIER CA",
        "WHITTER, CA",
        "WHITTIE CA",
        "SOUTH WHITTIER",
        "WHITIER CA",
        "NORTH WHITTIER CA",
        "NORTH WHITTIER",
        "WHITTIER",
        "NORTH WHITTIER",
        "WHITTIER CA CA",
        "WHITTIER/CA",
        "WHITTIER, CA",
        "WHITWOOD CA",
        "WHITTIER CA",
    ],
    "WILLOWBROOK": [
        "WILLOWBROOK CA",
        "WILLOWBROOKS CA",
        "WILLOWBROOK",
        "WILLOW BROOK CA",
    ],
    "WILMINGTON": ["WILMINTON CA", "WILMINGTON VA", "WILMINGTON", "WILMINGTON CA"],
    "WINDSOR HILLS": ["WINDSOR HILLS CA"],
    "WINNETKA": ["WINETKA CA", "WINNETKA CA", "WINNETKA, CA"],
    "WOODLAND HILLS": [
        "WOODLAND HILLS CA",
        "WOODLAND HILLS CALIF",
        "WOODLAND HILLS, CA",
        "WOODLAND HLS CA",
        "WOODLAND HILLS",
    ],
    "WRIGHTWOOD": ["WRIGHT WOOD CA", "WRIGHTWOOD CA", "WRIGHTWOOD"],
}
