#------------------------------------Southern California------------------------------------#

# Santa Ana constants

SANTA_ANA_PLANNING_URL = "https://www.santa-ana.org/major-planning-projects-and-monthly-development-project-reports/"
SANTA_ANA_PLANNING_OFFICE_EMAIL = 'planning@santa-ana.org'
SANTA_ANA_PLANNING_OFFICE_PHONE = '(714) 667-2732'
SANTA_ANA_PLANNING_OFFICE_NAME = 'Santa Ana Planning Office'

# City of Orange constants

ORANGE_PLANNING_URL = "https://www.cityoforange.org/our-city/departments/community-development/planning-division/current-projects"
ORANGE_PLANNING_OFFICE_EMAIL = 'cdinfo@cityoforange.org'
ORANGE_PLANNING_OFFICE_PHONE = '(714) 744-7220'
ORANGE_PLANNING_OFFICE_NAME = 'Orange Planning Office'

ORANGE_ROBERT_GARCIA_EMAIL = 'rgarcia@cityoforange.org'
ORANGE_ROBERT_GARCIA_PHONE = '(714) 744-7231'
ORANGE_ROBERT_GARCIA_NAME = 'Robert Garcia'

ORANGE_MONIQUE_SCHWARTZ_EMAIL = 'mschwartz@cityoforange.org'
ORANGE_MONIQUE_SCHWARTZ_PHONE = '(714) 744-7242'
ORANGE_MONIQUE_SCHWARTZ_NAME = 'Monique Schwartz'

ORANGE_VIDAL_F_MARQUEZ_EMAIL = 'vmarquez@cityoforange.org'
ORANGE_VIDAL_F_MARQUEZ_PHONE = '(714) 744-7241'
ORANGE_VIDAL_F_MARQUEZ_NAME = 'Vidal F. Márquez'

ORANGE_CHAD_ORTLIEB_EMAIL = 'cortega@cityoforange.org'
ORANGE_CHAD_ORTLIEB_PHONE = '(714) 744-7237'
ORANGE_CHAD_ORTLIEB_NAME = 'Chad Ortlieb'

ORANGE_RYAN_ABEGGLEN_EMAIL = 'rabegglen@cityoforange.org'
ORANGE_RYAN_ABEGGLEN_PHONE = '(714) 744-7252'
ORANGE_RYAN_ABEGGLEN_NAME = 'Ryan Agbayani'

ORANGE_MIKE_BOSTER_EMAIL = 'mboster@cityoforange.org'
ORANGE_MIKE_BOSTER_PHONE = '(714) 744-7203'
ORANGE_MIKE_BOSTER_NAME = 'Mike Boster'

ORANGE_ANI_MNATSAKANYAN_EMAIL = 'amatsumayan@cityoforange.org'
ORANGE_ANI_MNATSAKANYAN_PHONE = '(714) 744-7239'
ORANGE_ANI_MNATSAKANYAN_NAME = 'Ani Mnatsakanyan'

ORANGE_TIFFANY_CHHAN_EMAIL = 'tchhan@cityoforange.org'
ORANGE_TIFFANY_CHHAN_PHONE = '(714) 744-7272'
ORANGE_TIFFANY_CHHAN_NAME = 'Tiffany Chhan'

ORANGE_AMBER_GREGG_EMAIL = ORANGE_PLANNING_OFFICE_EMAIL
ORANGE_AMBER_GREGG_PHONE = ORANGE_PLANNING_OFFICE_PHONE
ORANGE_AMBER_GREGG_NAME = 'Amber Gregg'

ORANGE_MONIQUE_SCHWARTZ_EMAIL = 'mschwartz@cityoforange.org'
ORANGE_MONIQUE_SCHWARTZ_PHONE = ORANGE_PLANNING_OFFICE_PHONE
ORANGE_MONIQUE_SCHWARTZ_NAME = 'Monique Schwartz'

ORANGE_RAY_PASCUA_EMAIL = ORANGE_PLANNING_OFFICE_EMAIL
ORANGE_RAY_PASCUA_PHONE = ORANGE_PLANNING_OFFICE_PHONE
ORANGE_RAY_PASCUA_NAME = 'Ray Pascua'

orange_planner_emails = {

    ORANGE_ROBERT_GARCIA_NAME: ORANGE_ROBERT_GARCIA_EMAIL,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_EMAIL,
    ORANGE_VIDAL_F_MARQUEZ_NAME: ORANGE_VIDAL_F_MARQUEZ_EMAIL,
    ORANGE_CHAD_ORTLIEB_NAME: ORANGE_CHAD_ORTLIEB_EMAIL,
    ORANGE_RYAN_ABEGGLEN_NAME: ORANGE_RYAN_ABEGGLEN_EMAIL,
    ORANGE_MIKE_BOSTER_NAME: ORANGE_MIKE_BOSTER_EMAIL,
    ORANGE_ANI_MNATSAKANYAN_NAME: ORANGE_ANI_MNATSAKANYAN_EMAIL,
    ORANGE_TIFFANY_CHHAN_NAME: ORANGE_TIFFANY_CHHAN_EMAIL,
    ORANGE_AMBER_GREGG_NAME: ORANGE_AMBER_GREGG_EMAIL,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_EMAIL,
    ORANGE_RAY_PASCUA_NAME: ORANGE_RAY_PASCUA_EMAIL

}

orange_planner_phones = {

    ORANGE_ROBERT_GARCIA_NAME: ORANGE_ROBERT_GARCIA_PHONE,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_PHONE,
    ORANGE_VIDAL_F_MARQUEZ_NAME: ORANGE_VIDAL_F_MARQUEZ_PHONE,
    ORANGE_CHAD_ORTLIEB_NAME: ORANGE_CHAD_ORTLIEB_PHONE,
    ORANGE_RYAN_ABEGGLEN_NAME: ORANGE_RYAN_ABEGGLEN_PHONE,
    ORANGE_MIKE_BOSTER_NAME: ORANGE_MIKE_BOSTER_PHONE,
    ORANGE_ANI_MNATSAKANYAN_NAME: ORANGE_ANI_MNATSAKANYAN_PHONE,
    ORANGE_TIFFANY_CHHAN_NAME: ORANGE_TIFFANY_CHHAN_PHONE,
    ORANGE_AMBER_GREGG_NAME: ORANGE_AMBER_GREGG_PHONE,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_PHONE,
    ORANGE_RAY_PASCUA_NAME: ORANGE_RAY_PASCUA_PHONE
}

orange_planner_names = {

    ORANGE_ROBERT_GARCIA_NAME: ORANGE_ROBERT_GARCIA_NAME,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_NAME,
    ORANGE_VIDAL_F_MARQUEZ_NAME: ORANGE_VIDAL_F_MARQUEZ_NAME,
    ORANGE_CHAD_ORTLIEB_NAME: ORANGE_CHAD_ORTLIEB_NAME,
    ORANGE_RYAN_ABEGGLEN_NAME: ORANGE_RYAN_ABEGGLEN_NAME,
    ORANGE_MIKE_BOSTER_NAME: ORANGE_MIKE_BOSTER_NAME,
    ORANGE_ANI_MNATSAKANYAN_NAME: ORANGE_ANI_MNATSAKANYAN_NAME,
    ORANGE_TIFFANY_CHHAN_NAME: ORANGE_TIFFANY_CHHAN_NAME,
    ORANGE_AMBER_GREGG_NAME: ORANGE_AMBER_GREGG_NAME,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_NAME,
    ORANGE_RAY_PASCUA_NAME: ORANGE_RAY_PASCUA_NAME

}