#------------------------------------Southern California------------------------------------#


# Santa Ana constants

SANTA_ANA_PLANNING_URL = "https://www.santa-ana.org/major-planning-projects-and-monthly-development-project-reports/"
SANTA_ANA_PLANNING_OFFICE_EMAIL = 'planning@santa-ana.org'
SANTA_ANA_PLANNING_OFFICE_PHONE = '(714) 667-2732'
SANTA_ANA_PLANNING_OFFICE_NAME = 'Santa Ana Planning Office'

# City of Orange constants

ORANGE_PLANNING_URL = "https://www.cityoforange.org/our-city/departments/community-development/planning-division/current-projects"
ORANGE_PLANNING_OFFICE_EMAIL = 'cdinfo@cityoforange.org'
ORANGE_PLANNING_OFFICE_PHONE = '(714) 744-7220'
ORANGE_PLANNING_OFFICE_NAME = 'Orange Planning Office'

ORANGE_ROBERT_GARCIA_EMAIL = 'rgarcia@cityoforange.org'
ORANGE_ROBERT_GARCIA_PHONE = '(714) 744-7231'
ORANGE_ROBERT_GARCIA_NAME = 'Robert Garcia'

ORANGE_MONIQUE_SCHWARTZ_EMAIL = 'mschwartz@cityoforange.org'
ORANGE_MONIQUE_SCHWARTZ_PHONE = '(714) 744-7242'
ORANGE_MONIQUE_SCHWARTZ_NAME = 'Monique Schwartz'

ORANGE_VIDAL_F_MARQUEZ_EMAIL = 'vmarquez@cityoforange.org'
ORANGE_VIDAL_F_MARQUEZ_PHONE = '(714) 744-7241'
ORANGE_VIDAL_F_MARQUEZ_NAME = 'Vidal F. Márquez'

ORANGE_CHAD_ORTLIEB_EMAIL = 'cortega@cityoforange.org'
ORANGE_CHAD_ORTLIEB_PHONE = '(714) 744-7237'
ORANGE_CHAD_ORTLIEB_NAME = 'Chad Ortlieb'

ORANGE_RYAN_ABEGGLEN_EMAIL = 'rabegglen@cityoforange.org'
ORANGE_RYAN_ABEGGLEN_PHONE = '(714) 744-7252'
ORANGE_RYAN_ABEGGLEN_NAME = 'Ryan Agbayani'

ORANGE_MIKE_BOSTER_EMAIL = 'mboster@cityoforange.org'
ORANGE_MIKE_BOSTER_PHONE = '(714) 744-7203'
ORANGE_MIKE_BOSTER_NAME = 'Mike Boster'

ORANGE_ANI_MNATSAKANYAN_EMAIL = 'amatsumayan@cityoforange.org'
ORANGE_ANI_MNATSAKANYAN_PHONE = '(714) 744-7239'
ORANGE_ANI_MNATSAKANYAN_NAME = 'Ani Mnatsakanyan'

ORANGE_TIFFANY_CHHAN_EMAIL = 'tchhan@cityoforange.org'
ORANGE_TIFFANY_CHHAN_PHONE = '(714) 744-7272'
ORANGE_TIFFANY_CHHAN_NAME = 'Tiffany Chhan'

ORANGE_AMBER_GREGG_EMAIL = ORANGE_PLANNING_OFFICE_EMAIL
ORANGE_AMBER_GREGG_PHONE = ORANGE_PLANNING_OFFICE_PHONE
ORANGE_AMBER_GREGG_NAME = 'Amber Gregg'

ORANGE_MONIQUE_SCHWARTZ_EMAIL = 'mschwartz@cityoforange.org'
ORANGE_MONIQUE_SCHWARTZ_PHONE = ORANGE_PLANNING_OFFICE_PHONE
ORANGE_MONIQUE_SCHWARTZ_NAME = 'Monique Schwartz'

ORANGE_RAY_PASCUA_EMAIL = ORANGE_PLANNING_OFFICE_EMAIL
ORANGE_RAY_PASCUA_PHONE = ORANGE_PLANNING_OFFICE_PHONE
ORANGE_RAY_PASCUA_NAME = 'Ray Pascua'

orange_planner_emails = {

    ORANGE_ROBERT_GARCIA_NAME: ORANGE_ROBERT_GARCIA_EMAIL,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_EMAIL,
    ORANGE_VIDAL_F_MARQUEZ_NAME: ORANGE_VIDAL_F_MARQUEZ_EMAIL,
    ORANGE_CHAD_ORTLIEB_NAME: ORANGE_CHAD_ORTLIEB_EMAIL,
    ORANGE_RYAN_ABEGGLEN_NAME: ORANGE_RYAN_ABEGGLEN_EMAIL,
    ORANGE_MIKE_BOSTER_NAME: ORANGE_MIKE_BOSTER_EMAIL,
    ORANGE_ANI_MNATSAKANYAN_NAME: ORANGE_ANI_MNATSAKANYAN_EMAIL,
    ORANGE_TIFFANY_CHHAN_NAME: ORANGE_TIFFANY_CHHAN_EMAIL,
    ORANGE_AMBER_GREGG_NAME: ORANGE_AMBER_GREGG_EMAIL,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_EMAIL,
    ORANGE_RAY_PASCUA_NAME: ORANGE_RAY_PASCUA_EMAIL

}

orange_planner_phones = {

    ORANGE_ROBERT_GARCIA_NAME: ORANGE_ROBERT_GARCIA_PHONE,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_PHONE,
    ORANGE_VIDAL_F_MARQUEZ_NAME: ORANGE_VIDAL_F_MARQUEZ_PHONE,
    ORANGE_CHAD_ORTLIEB_NAME: ORANGE_CHAD_ORTLIEB_PHONE,
    ORANGE_RYAN_ABEGGLEN_NAME: ORANGE_RYAN_ABEGGLEN_PHONE,
    ORANGE_MIKE_BOSTER_NAME: ORANGE_MIKE_BOSTER_PHONE,
    ORANGE_ANI_MNATSAKANYAN_NAME: ORANGE_ANI_MNATSAKANYAN_PHONE,
    ORANGE_TIFFANY_CHHAN_NAME: ORANGE_TIFFANY_CHHAN_PHONE,
    ORANGE_AMBER_GREGG_NAME: ORANGE_AMBER_GREGG_PHONE,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_PHONE,
    ORANGE_RAY_PASCUA_NAME: ORANGE_RAY_PASCUA_PHONE
}

orange_planner_names = {

    ORANGE_ROBERT_GARCIA_NAME: ORANGE_ROBERT_GARCIA_NAME,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_NAME,
    ORANGE_VIDAL_F_MARQUEZ_NAME: ORANGE_VIDAL_F_MARQUEZ_NAME,
    ORANGE_CHAD_ORTLIEB_NAME: ORANGE_CHAD_ORTLIEB_NAME,
    ORANGE_RYAN_ABEGGLEN_NAME: ORANGE_RYAN_ABEGGLEN_NAME,
    ORANGE_MIKE_BOSTER_NAME: ORANGE_MIKE_BOSTER_NAME,
    ORANGE_ANI_MNATSAKANYAN_NAME: ORANGE_ANI_MNATSAKANYAN_NAME,
    ORANGE_TIFFANY_CHHAN_NAME: ORANGE_TIFFANY_CHHAN_NAME,
    ORANGE_AMBER_GREGG_NAME: ORANGE_AMBER_GREGG_NAME,
    ORANGE_MONIQUE_SCHWARTZ_NAME: ORANGE_MONIQUE_SCHWARTZ_NAME,
    ORANGE_RAY_PASCUA_NAME: ORANGE_RAY_PASCUA_NAME

}

# City of Anaheim constants

ANAHEIM_PLANNING_URL = "https://www.anaheim.net/3348/Development-Activity"

ANAHEIM_ANDYS_MAP_URL = "https://gis.anaheim.net/andysmap/"

ANAHEIM_ANDYS_MAP_CSV = "AndysMap.csv"

ANAHEIM_RECENT_APPLICATIONS_CSV = "dev_apps.csv"

ANAHEIM_PLANNING_OFFICE_EMAIL = 'Planning@anaheim.net'

ANAHEIM_PLANNING_OFFICE_PHONE = '(714) 765-5139'


# Constants for the names
ANAHEIM_VICTORIA_TICORAT_NAME = "Victoria Ticorat"
ANAHEIM_SCOTT_KOEHM_NAME = "Scott Koehm"
ANAHEIM_HEATHER_FLORES_NAME = "Heather Flores"
ANAHEIM_NICHOLAS_TAYLOR_NAME = "Nicholas Taylor"
ANAHEIM_IVAN_OROZCO_NAME = "Ivan Orozco"
ANAHEIM_THOMAS_GORHAM_NAME = "Thomas Gorham"
ANAHEIM_MAGGIE_ZARAGOZA_NAME = "Maggie Zaragoza"
ANAHEIM_HEATHER_ALLEN_NAME = "Heather Allen"
ANAHEIM_ELAIN_THIENPRASIDDHI_NAME = "Elaine Thienprasiddhi"
ANAHEIM_CHRISTINE_NGUYEN_NAME = "Christine Nguyen"
ANAHEIM_AMANDA_LAFFER_NAME = "Amanda Laufer"
ANAHEIM_CHARLES_GUIAM_NAME = "Charles Guiam"
ANAHEIM_SEAN_NICHOLAS_NAME = "Sean Nicholas"
ANAHEIM_JUDY_DADANT_NAME = "Judy Dadant"
ANAHEIM_LISANDRO_OROZCO_NAME = "Lisandro Orozco"
ANAHEIM_JOSE_BARRIGA_NAME = "Jose Barriga"
ANAHEIM_DARREN_PARKER_NAME = "Darren Parker"
ANAHEIM_ARLETTE_KIM_NAME = "Arlette Kim"
ANAHEIM_NICHOLAS_BARRERA_NAME = "Nicholas Barrera"
ANAHEIM_MICHAEL_SOLIS_NAME = "Michael Solis"
ANAHEIM_LAURA_RODRIGUEZ_NAME = "Laura Rodriguez"
ANAHEIM_VINCE_FREGOSO_NAME = "Vince Fregoso"
ANAHEIM_ELBET_OLMEDO_NAME = "Eibet Olmedo"
ANAHEIM_MARY_MONTGOMERY_NAME = "Mary Montgomery"

# Constants for the phone numbers
ANAHEIM_VICTORIA_TICORAT_PHONE = "(714) 765-5011"
ANAHEIM_SCOTT_KOEHM_PHONE = "(714) 765-5395"
ANAHEIM_HEATHER_FLORES_PHONE = "(714) 765-5351"
ANAHEIM_NICHOLAS_TAYLOR_PHONE = "(714) 765-4323"
ANAHEIM_IVAN_OROZCO_PHONE = "(714) 765-4948"
ANAHEIM_THOMAS_GORHAM_PHONE = "(714) 765-4947"
ANAHEIM_MAGGIE_ZARAGOZA_PHONE = "(714) 765-5139 ex. 5832"
ANAHEIM_HEATHER_ALLEN_PHONE = "(714) 765-4958"
ANAHEIM_ELAIN_THIENPRASIDDHI_PHONE = "(714) 765-4568"
ANAHEIM_CHRISTINE_NGUYEN_PHONE = "(714) 765-4942"
ANAHEIM_AMANDA_LAFFER_PHONE = "(714) 765-4479"
ANAHEIM_CHARLES_GUIAM_PHONE = "(714) 765-5149"
ANAHEIM_SEAN_NICHOLAS_PHONE = "(714) 765-4968"
ANAHEIM_JUDY_DADANT_PHONE = "(714) 765-4945"
ANAHEIM_LISANDRO_OROZCO_PHONE = "(714) 765-5381"
ANAHEIM_JOSE_BARRIGA_PHONE = "(714) 765-5380"
ANAHEIM_DARREN_PARKER_PHONE = "(714) 765-5238"
ANAHEIM_ARLETTE_KIM_PHONE = "(714) 765-4959"
ANAHEIM_NICHOLAS_BARRERA_PHONE = "(714) 765-5230"
ANAHEIM_MICHAEL_SOLIS_PHONE = "(714) 765-5009"
ANAHEIM_LAURA_RODRIGUEZ_PHONE = "(714) 765-4391"
ANAHEIM_VINCE_FREGOSO_PHONE = "(714) 765-5355"
ANAHEIM_ELBET_OLMEDO_PHONE = "(714) 765-5363"
ANAHEIM_MARY_MONTGOMERY_PHONE = "(714) 765-5342"

# Constants for emails
ANAHEIM_VICTORIA_TICORAT_EMAIL = "VTICORAT@ANAHEIM.NET"
ANAHEIM_SCOTT_KOEHM_EMAIL = "skoehm@anaheim.net"
ANAHEIM_HEATHER_FLORES_EMAIL = "skoehm@anaheim.net"
ANAHEIM_NICHOLAS_TAYLOR_EMAIL = "njtaylor@anaheim.net"
ANAHEIM_IVAN_OROZCO_EMAIL = "iorozco@anaheim.net"
ANAHEIM_THOMAS_GORHAM_EMAIL = "TGorham@Anaheim.net"
ANAHEIM_MAGGIE_ZARAGOZA_EMAIL = "MZaragoza@anaheim.net"
ANAHEIM_HEATHER_ALLEN_EMAIL = "HAllen@anaheim.net"
ANAHEIM_ELAIN_THIENPRASIDDHI_EMAIL = "EThien@anaheim.net"
ANAHEIM_CHRISTINE_NGUYEN_EMAIL = "CNGUYEN2@ANAHEIM.NET"
ANAHEIM_AMANDA_LAFFER_EMAIL = "ALauffer@Anaheim.net"
ANAHEIM_CHARLES_GUIAM_EMAIL = "CMGuiam@anaheim.net"
ANAHEIM_SEAN_NICHOLAS_EMAIL = "SNicholas@anaheim.net"
ANAHEIM_JUDY_DADANT_EMAIL = "JDadant@anaheim.net"
ANAHEIM_LISANDRO_OROZCO_EMAIL = "LOROZCO@ANAHEIM.NET"
ANAHEIM_JOSE_BARRIGA_EMAIL = "JMBarriga@Anaheim.net"
ANAHEIM_DARREN_PARKER_EMAIL = "DParker@anaheim.net"
ANAHEIM_ARLETTE_KIM_EMAIL = ANAHEIM_PLANNING_OFFICE_EMAIL
ANAHEIM_NICHOLAS_BARRERA_EMAIL = "NBARRERA@ANAHEIM.NET"
ANAHEIM_MICHAEL_SOLIS_EMAIL = "msolis@anaheim.net"
ANAHEIM_LAURA_RODRIGUEZ_EMAIL = "larodriquez@anaheim.net"
ANAHEIM_VINCE_FREGOSO_EMAIL = "vfregoso@anaheim.net"
ANAHEIM_ELBET_OLMEDO_EMAIL = "eolmedo@anaheim.net"
ANAHEIM_MARY_MONTGOMERY_EMAIL = "mmontgomery@anaheim.net"
# List of names
anaheim_planner_names = {
    ANAHEIM_VICTORIA_TICORAT_NAME: 'Victoria Ticorat',
    ANAHEIM_SCOTT_KOEHM_NAME: 'Scott Koehm',
    ANAHEIM_HEATHER_FLORES_NAME: 'Heather Flores',
    ANAHEIM_NICHOLAS_TAYLOR_NAME: 'Nicholas Taylor',
    ANAHEIM_IVAN_OROZCO_NAME: 'Ivan Orozco',
    ANAHEIM_THOMAS_GORHAM_NAME: 'Thomas Gorham',
    ANAHEIM_MAGGIE_ZARAGOZA_NAME: 'Maggie Zaragoza',
    ANAHEIM_HEATHER_ALLEN_NAME: 'Heather Allen',
    ANAHEIM_ELAIN_THIENPRASIDDHI_NAME: 'Elain Thienprasiddhi',
    ANAHEIM_CHRISTINE_NGUYEN_NAME: 'Christine Nguyen',
    ANAHEIM_AMANDA_LAFFER_NAME: 'Amanda Laffer',
    ANAHEIM_CHARLES_GUIAM_NAME: 'Charles Guiam',
    ANAHEIM_SEAN_NICHOLAS_NAME: 'Sean Nicholas',
    ANAHEIM_JUDY_DADANT_NAME: 'Judy Dadant',
    ANAHEIM_LISANDRO_OROZCO_NAME: 'Lisandro Orozco',
    ANAHEIM_JOSE_BARRIGA_NAME: 'Jose Barriga',
    ANAHEIM_DARREN_PARKER_NAME: 'Darren Parker',
    ANAHEIM_ARLETTE_KIM_NAME: 'Arlette Kim',
    ANAHEIM_NICHOLAS_BARRERA_NAME: 'Nicholas Barrera',
    ANAHEIM_MICHAEL_SOLIS_NAME: 'Michael Solis',
    ANAHEIM_LAURA_RODRIGUEZ_NAME: 'Laura Rodriguez',
    ANAHEIM_VINCE_FREGOSO_NAME: 'Vince Fregoso',
    ANAHEIM_ELBET_OLMEDO_NAME: 'Elbet Olmedo',
    ANAHEIM_MARY_MONTGOMERY_NAME: 'Mary Montgomery'
}

# List of emails
anaheim_planner_emails = {
    ANAHEIM_VICTORIA_TICORAT_NAME: ANAHEIM_VICTORIA_TICORAT_EMAIL,
    ANAHEIM_SCOTT_KOEHM_NAME: ANAHEIM_SCOTT_KOEHM_EMAIL,
    ANAHEIM_HEATHER_FLORES_NAME: ANAHEIM_HEATHER_FLORES_EMAIL,
    ANAHEIM_NICHOLAS_TAYLOR_NAME: ANAHEIM_NICHOLAS_TAYLOR_EMAIL,
    ANAHEIM_IVAN_OROZCO_NAME: ANAHEIM_IVAN_OROZCO_EMAIL,
    ANAHEIM_THOMAS_GORHAM_NAME: ANAHEIM_THOMAS_GORHAM_EMAIL,
    ANAHEIM_MAGGIE_ZARAGOZA_NAME: ANAHEIM_MAGGIE_ZARAGOZA_EMAIL,
    ANAHEIM_HEATHER_ALLEN_NAME: ANAHEIM_HEATHER_ALLEN_EMAIL,
    ANAHEIM_ELAIN_THIENPRASIDDHI_NAME: ANAHEIM_ELAIN_THIENPRASIDDHI_EMAIL,
    ANAHEIM_CHRISTINE_NGUYEN_NAME: ANAHEIM_CHRISTINE_NGUYEN_EMAIL,
    ANAHEIM_AMANDA_LAFFER_NAME: ANAHEIM_AMANDA_LAFFER_EMAIL,
    ANAHEIM_CHARLES_GUIAM_NAME: ANAHEIM_CHARLES_GUIAM_EMAIL,
    ANAHEIM_SEAN_NICHOLAS_NAME: ANAHEIM_SEAN_NICHOLAS_EMAIL,
    ANAHEIM_JUDY_DADANT_NAME: ANAHEIM_JUDY_DADANT_EMAIL,
    ANAHEIM_LISANDRO_OROZCO_NAME: ANAHEIM_LISANDRO_OROZCO_EMAIL,
    ANAHEIM_JOSE_BARRIGA_NAME: ANAHEIM_JOSE_BARRIGA_EMAIL,
    ANAHEIM_DARREN_PARKER_NAME: ANAHEIM_DARREN_PARKER_EMAIL,
    ANAHEIM_ARLETTE_KIM_NAME: ANAHEIM_ARLETTE_KIM_EMAIL,
    ANAHEIM_NICHOLAS_BARRERA_NAME: ANAHEIM_NICHOLAS_BARRERA_EMAIL,
    ANAHEIM_MICHAEL_SOLIS_NAME: ANAHEIM_MICHAEL_SOLIS_EMAIL,
    ANAHEIM_LAURA_RODRIGUEZ_NAME: ANAHEIM_LAURA_RODRIGUEZ_EMAIL,
    ANAHEIM_VINCE_FREGOSO_NAME: ANAHEIM_VINCE_FREGOSO_EMAIL,
    ANAHEIM_ELBET_OLMEDO_NAME: ANAHEIM_ELBET_OLMEDO_EMAIL,
    ANAHEIM_MARY_MONTGOMERY_NAME: ANAHEIM_MARY_MONTGOMERY_EMAIL
}

# List of names and phone numbers
anaheim_planner_phones = {
    ANAHEIM_VICTORIA_TICORAT_NAME: ANAHEIM_VICTORIA_TICORAT_PHONE,
    ANAHEIM_SCOTT_KOEHM_NAME: ANAHEIM_SCOTT_KOEHM_PHONE,
    ANAHEIM_HEATHER_FLORES_NAME: ANAHEIM_HEATHER_FLORES_PHONE,
    ANAHEIM_NICHOLAS_TAYLOR_NAME: ANAHEIM_NICHOLAS_TAYLOR_PHONE,
    ANAHEIM_IVAN_OROZCO_NAME: ANAHEIM_IVAN_OROZCO_PHONE,
    ANAHEIM_THOMAS_GORHAM_NAME: ANAHEIM_THOMAS_GORHAM_PHONE,
    ANAHEIM_MAGGIE_ZARAGOZA_NAME: ANAHEIM_MAGGIE_ZARAGOZA_PHONE,
    ANAHEIM_HEATHER_ALLEN_NAME: ANAHEIM_HEATHER_ALLEN_PHONE,
    ANAHEIM_ELAIN_THIENPRASIDDHI_NAME: ANAHEIM_ELAIN_THIENPRASIDDHI_PHONE,
    ANAHEIM_CHRISTINE_NGUYEN_NAME: ANAHEIM_CHRISTINE_NGUYEN_PHONE,
    ANAHEIM_AMANDA_LAFFER_NAME: ANAHEIM_AMANDA_LAFFER_PHONE,
    ANAHEIM_CHARLES_GUIAM_NAME: ANAHEIM_CHARLES_GUIAM_PHONE,
    ANAHEIM_SEAN_NICHOLAS_NAME: ANAHEIM_SEAN_NICHOLAS_PHONE,
    ANAHEIM_JUDY_DADANT_NAME: ANAHEIM_JUDY_DADANT_PHONE,
    ANAHEIM_LISANDRO_OROZCO_NAME: ANAHEIM_LISANDRO_OROZCO_PHONE,
    ANAHEIM_JOSE_BARRIGA_NAME: ANAHEIM_JOSE_BARRIGA_PHONE,
    ANAHEIM_DARREN_PARKER_NAME: ANAHEIM_DARREN_PARKER_PHONE,
    ANAHEIM_ARLETTE_KIM_NAME: ANAHEIM_ARLETTE_KIM_PHONE,
    ANAHEIM_NICHOLAS_BARRERA_NAME: ANAHEIM_NICHOLAS_BARRERA_PHONE,
    ANAHEIM_MICHAEL_SOLIS_NAME: ANAHEIM_MICHAEL_SOLIS_PHONE,
    ANAHEIM_LAURA_RODRIGUEZ_NAME: ANAHEIM_LAURA_RODRIGUEZ_PHONE,
    ANAHEIM_VINCE_FREGOSO_NAME: ANAHEIM_VINCE_FREGOSO_PHONE,
    ANAHEIM_ELBET_OLMEDO_NAME: ANAHEIM_ELBET_OLMEDO_PHONE,
    ANAHEIM_MARY_MONTGOMERY_NAME: ANAHEIM_MARY_MONTGOMERY_PHONE
}


